### ISSUE TITLE
Bootstrap 5.0.1 and Angular 12

### ISSUE THREAD

**Issue by hugoebarboza** [twbs/bootstrap-npm-starter#55] opened 2021-05-27 14:42 UTC
Is there guidance to install bootstrap with Angular 12 ?

Recently, I upgrade my Angular project to Bootstrap 5 but all bootstrap functionality crashed.

**Comment by mdo** [comment] 2021-05-27 17:03
Closing as a duplicate of https://github.com/twbs/bootstrap/discussions/34127. This is an npm starter project that doesn't use Angular, so I can't help you there.

**Closed by mdo** 2021-05-27 17:03 UTC

**Comment by hugoebarboza** [comment] 2021-05-27 17:32
Hi @mdo, but Bootstrap 5 supports Angular ?
